# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528792dc08cec06f0a506f15ebe25eca89828240a91be001d56b62aa2d60c9d8fcd6fde4f2f50ff02734e3f4ce40b58d9839dc4c93d0d8da57fef9d6195becce

test:
  secret_key_base: 7a5d98a39f033b48cdd21a5ac505f70e2c5e476636c26656010a79ab64b09e49bad556a37a73aa28bbf5e53a30fc04e47919721b78ed347cb76d291000bf9196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
